name = input("What is your name?")
age = input("How old are you?")
city = input("Where do you live?")
occupation = input("What do you do for a living?")
print("Hello, " + name + "! Nice to meet you. You are " + age + " years old, you live in " + city + ", and you work as a " + occupation + ".")